In [1]:
import numpy as np
import pandas as pd

In [2]:
np.__version__

'1.19.5'

In [3]:
pd.__version__

'1.1.5'

In [4]:
!wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv

--2021-09-13 09:29:13--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1.4M) [text/plain]
Saving to: ‘data.csv’

data.csv            100%[===================>]   1.41M  --.-KB/s    in 0.05s   

2021-09-13 09:29:13 (28.2 MB/s) - ‘data.csv’ saved [1475504/1475504]



In [5]:
!ls


data.csv  sample_data


In [6]:
data=pd.read_csv('data.csv')

In [7]:
data.head()

Make       Model  Year  ... city mpg  Popularity   MSRP
0  BMW  1 Series M  2011  ...       19        3916  46135
1  BMW    1 Series  2011  ...       19        3916  40650
2  BMW    1 Series  2011  ...       20        3916  36350
3  BMW    1 Series  2011  ...       18        3916  29450
4  BMW    1 Series  2011  ...       18        3916  34500

[5 rows x 16 columns]

In [36]:
df_bmw=data[
            data['Make']=='BMW'
]
df_bmw.MSRP.mean()

61546.76347305389

In [8]:
df_bmw=data[
            data['Year']>=2015
]
df_bmw

Make       Model  Year  ... city mpg  Popularity   MSRP
32     FIAT  124 Spider  2017  ...       26         819  27495
33     FIAT  124 Spider  2017  ...       26         819  24995
34     FIAT  124 Spider  2017  ...       26         819  28195
41      BMW    2 Series  2016  ...       23        3916  32850
42      BMW    2 Series  2016  ...       23        3916  38650
...     ...         ...   ...  ...      ...         ...    ...
11898   BMW          Z4  2015  ...       17        3916  56950
11899   BMW          Z4  2015  ...       17        3916  65800
11900   BMW          Z4  2016  ...       17        3916  57500
11901   BMW          Z4  2016  ...       22        3916  49700
11902   BMW          Z4  2016  ...       17        3916  66350

[5995 rows x 16 columns]

In [9]:
df_bmw['Engine HP'].isnull().sum()

51

In [10]:
mean_hp_before=df_bmw['Engine HP'].mean()
mean_hp_before

272.98771870794076

In [11]:
df_bmw['Engine HP'].fillna(mean_hp_before)

32       160.0
33       160.0
34       160.0
41       240.0
42       240.0
         ...  
11898    300.0
11899    335.0
11900    300.0
11901    240.0
11902    335.0
Name: Engine HP, Length: 5995, dtype: float64

In [12]:
mean_hp_after=df_bmw['Engine HP'].mean()
mean_hp_after

272.98771870794076

In [15]:
df_rolls_royce=data[
                    (data['Make']=='Rolls-Royce')
]
df_rolls_reduced=df_rolls_royce[['Engine HP','Engine Cylinders','highway MPG']]

In [16]:
df_rolls_reduced

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5276       563.0              12.0           21
5277       563.0              12.0           21
5278       563.0              12.0           21
5279       563.0              12.0           20
5280       563.0              12.0           20
5281       563.0              12.0           21
5282       563.0              12.0           21
5283       563.0              12.0           21
5284       563.0              12.0           21
7443       322.0              12.0           15
7444       322.0              12.0           15
7553       453.0              12.0           19
7554       453.0              12.0           19
7555       453.0              12.0           19
7556       453.0              12.0           19
7557       453.0              12.0           19
7558       453.0              12.0           19
7559       453.0              12.0           19
7560       453.0              12.0           19
7561       453.0              12.0           19
7562       453.0              12.0           19
7563       453.0              12.0           19
7564       453.0              12.0           19
9431       322.0              12.0           15
9432       322.0              12.0           15
11448      624.0              12.0           21
11449      624.0              12.0           21
11450      624.0              12.0           21

In [18]:
df_rolls_reduced=df_rolls_reduced.drop_duplicates()
df_rolls_reduced

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [20]:
X=df_rolls_reduced.values

In [21]:
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [22]:
XTX=X.T.dot(X)
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [26]:
XTX_inv=np.linalg.inv(XTX)
XTX_inv

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [27]:
XTX_inv.sum()

0.032212320677486125

In [29]:
y=np.array([1000, 1100, 900, 1200, 1000, 850, 1300])
y

array([1000, 1100,  900, 1200, 1000,  850, 1300])

In [32]:
w=XTX_inv.dot(X.T).dot(y)

In [38]:
w[0]

0.19989598183188978